# Generated by Django 3.2.4 on 2021-06-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20201023_1019'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='starred_boards',
            field=models.ManyToManyField(blank=True, to='boards.Board'),
        ),
    ]
